name: Test

on: [ push ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [
          ubuntu-latest,
          macos-latest,
          windows-latest,
        ]
        toolchain: [
          stable,
          #beta,
          #nightly,
        ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Rust Toolchain
        run: |
          rustup toolchain install ${{ matrix.toolchain }} --profile minimal --no-self-update
          rustup default ${{ matrix.toolchain }}

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Install vcpkg Packages
        if: matrix.os == 'windows-latest'
        uses: johnwason/vcpkg-action@v6
        id: vcpkg
        with:
          pkgs: libsodium
          triplet: x64-windows-release
          token: ${{ github.token }}
          github-binarycache: true

      - name: Make Test Windows
        if: matrix.os == 'windows-latest'
        run: |-
          $env:SODIUM_LIB_DIR="$(pwd)\vcpkg\packages\libsodium_x64-windows-release\lib"
          make test

      - name: Make Test
        if: matrix.os != 'windows-latest'
        run: make test
